import {chromium,expect} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {execFileSync} from 'node:child_process';
const root=fileURLToPath(new URL('../',import.meta.url)),out=path.join(root,'artifacts/browser');await fs.mkdir(out,{recursive:true});const base=process.env.BASE_URL||'http://127.0.0.1:4173/web/';
const launch={headless:true,chromiumSandbox:true};if(process.env.CHROMIUM_EXECUTABLE_PATH)launch.executablePath=process.env.CHROMIUM_EXECUTABLE_PATH;
const browser=await chromium.launch(launch);const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true,reducedMotion:'reduce'});const page=await context.newPage();const pageErrors=[],checks=[],externalRequests=[];context.on('request',request=>{if(/^https?:/.test(request.url())&&new URL(request.url()).origin!==new URL(base).origin)externalRequests.push(request.url());});page.on('pageerror',e=>pageErrors.push(e.message));
const cdp=await browser.newBrowserCDPSession();const commandLine=await cdp.send('Browser.getBrowserCommandLine');expect(commandLine.arguments).not.toContain('--no-sandbox');expect(commandLine.arguments).not.toContain('--disable-setuid-sandbox');
const ready=async()=>{await expect(page.locator('#minimum-changes')).toHaveText('2');await expect(page.locator('#greedy-changes')).toHaveText('3');await expect(page.locator('#download-zip')).toBeEnabled();};
const demo=async()=>{await page.locator('#load-demo').click();await ready();};
const noOverflow=async()=>expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBeTruthy();
async function check(name,fn){await fn();checks.push({name,status:'PASS'});console.log('PASS',name);}
async function printDownloadedChecklist(archive,prefix) {
 // Extract the exact downloaded document with Python's independent ZIP reader.
 const html=execFileSync('python3',['-c','import sys,zipfile; z=zipfile.ZipFile(sys.argv[1]); assert z.testzip() is None; sys.stdout.buffer.write(z.read("loading-checklist.html"))',archive],{encoding:'utf8',maxBuffer:16*1024*1024});
 await fs.writeFile(path.join(out,prefix+'.html'),html);
 const printPage=await context.newPage();
 try {
  await printPage.setViewportSize({width:794,height:1123});await printPage.setContent(html);await printPage.evaluate(()=>document.fonts.ready);await printPage.emulateMedia({media:'print'});
  await expect(printPage.locator('.job')).toHaveCount(3);
  expect(await printPage.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBeTruthy();
  await expect(printPage.locator('body')).toContainText('Original STOPs retained: 1');
  await printPage.screenshot({path:path.join(out,prefix+'-print-media.png'),fullPage:true});
  await printPage.pdf({path:path.join(out,prefix+'.pdf'),printBackground:true,preferCSSPageSize:true});
 } finally {await printPage.close();}
}
try{
 await page.goto(base);await ready();await page.evaluate(()=>document.fonts.ready);
 await check('Japanese canonical optimum, physical needle sequence and privacy',async()=>{await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('[data-testid="job-card"]')).toHaveCount(3);await expect(page.locator('[data-testid="plan-step"]').last().locator('[data-testid="needle-sequence"]')).toHaveAttribute('aria-label','1, 2, 1, 2');await noOverflow();await page.screenshot({path:path.join(out,'desktop-ja.png'),fullPage:true});});
 await check('Real ZIP and JSON downloads',async()=>{const wait=page.waitForEvent('download');await page.locator('#download-zip').click();const download=await wait;expect(download.suggestedFilename()).toBe('needle-batch.zip');await download.saveAs(path.join(out,'downloaded.zip'));const waitJson=page.waitForEvent('download');await page.locator('#download-json').click();const json=await waitJson;await json.saveAs(path.join(out,'downloaded-manifest.json'));const m=JSON.parse(await fs.readFile(path.join(out,'downloaded-manifest.json'),'utf8'));const zippedManifest=JSON.parse(execFileSync('python3',['-c','import sys,zipfile; sys.stdout.buffer.write(zipfile.ZipFile(sys.argv[1]).read("manifest.json"))',path.join(out,'downloaded.zip')],{encoding:'utf8'}));expect(m).toEqual(zippedManifest);expect(m.minimumChanges).toBe(2);expect(m.jobs[2].needleSequence).toEqual([1,2,1,2]);expect(m.jobs[0].stopCount).toBe(1);});
 await check('Actual downloaded checklist renders and prints to PDF',async()=>{await printDownloadedChecklist(path.join(out,'downloaded.zip'),'loading-checklist');});
 await check('English switch preserves valid plan; keyboard can calculate',async()=>{await page.locator('[data-lang="en"]').click();await expect(page.locator('html')).toHaveAttribute('lang','en');await ready();await page.locator('#optimize').focus();await page.keyboard.press('Enter');await ready();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'desktop-en.png'),fullPage:true});});
 await check('Current load edit clears stale result immediately',async()=>{await page.locator('#needle-thread-0').fill('X');await expect(page.locator('#download-zip')).toBeDisabled();await expect(page.locator('#minimum-changes')).toHaveCount(0);await page.locator('#optimize').click();await expect(page.locator('#minimum-changes')).toHaveText('3');await demo();});
 await check('Mapping edit invalidates and rejects incomplete identity',async()=>{await page.locator('#map-0-1').fill('');await expect(page.locator('#download-json')).toBeDisabled();await page.locator('#optimize').click();await expect(page.locator('#error')).toBeVisible();await expect(page.locator('#download-zip')).toBeDisabled();await page.screenshot({path:path.join(out,'invalid-mapping-en.png'),fullPage:true});await demo();});
 await check('All locked makes missing C infeasible; unavailable L preserves optimum',async()=>{await page.locator('[data-needle="0"][data-field="locked"]').check();await page.locator('[data-needle="1"][data-field="locked"]').check();await page.locator('#optimize').click();await expect(page.locator('#status')).toContainText('cannot cover');await expect(page.locator('#download-zip')).toBeDisabled();await demo();await page.locator('[data-needle="2"][data-field="unavailable"]').check();await page.locator('#optimize').click();await ready();await demo();});
 await check('Job reordering and reset cannot retain old result',async()=>{await page.locator('[data-action="down"][data-index="0"]').click();await expect(page.locator('[data-testid="job-card"]').first().locator('h3')).toHaveText('02-a.u01');await expect(page.locator('#download-zip')).toBeDisabled();await page.locator('#reset-empty').click();await expect(page.locator('[data-testid="job-card"]')).toHaveCount(0);await expect(page.locator('#download-zip')).toBeDisabled();await expect(page.locator('#optimize')).toBeDisabled();await demo();});
 await check('Physical needle duplicate and over-capacity constraints',async()=>{await page.locator('#needle-number-0').fill('2');await page.locator('#optimize').click();await expect(page.locator('#error')).toBeVisible();await expect(page.locator('#download-zip')).toBeDisabled();await demo();await page.locator('#add-needle').click();await page.locator('#add-needle').click();await page.locator('#add-needle').click();await page.locator('#add-needle').click();await expect(page.locator('[data-needle="6"][data-field="unavailable"]')).toBeChecked();await page.locator('[data-needle="6"][data-field="unavailable"]').uncheck();await page.locator('#optimize').click();await expect(page.locator('#error')).toBeVisible();await demo();});
 await check('Native file import, explicit mappings, same optimum',async()=>{await page.locator('#reset-empty').click();await page.locator('#file-input').setInputFiles(['01-c.u01','02-a.u01','03-bcbc.u01'].map(n=>path.join(root,'fixtures',n)));await expect(page.locator('[data-testid="job-card"]')).toHaveCount(3);await page.locator('#needle-thread-0').fill('A');await page.locator('#needle-thread-1').fill('B');await page.locator('#map-0-1').fill('C');await page.locator('#map-1-2').fill('A');await page.locator('#map-2-3').fill('B');await page.locator('#map-2-4').fill('C');await page.locator('#optimize').click();await ready();});
 await check('Malformed and wrong-extension imports invalidate export without partial insertion',async()=>{await page.locator('#file-input').setInputFiles({name:'bad.u01',mimeType:'application/octet-stream',buffer:Buffer.from([1,2,3])});await expect(page.locator('#error')).toBeVisible();await expect(page.locator('[data-testid="job-card"]')).toHaveCount(3);await expect(page.locator('#download-zip')).toBeDisabled();await demo();await page.locator('#file-input').setInputFiles({name:'wrong.dst',mimeType:'application/octet-stream',buffer:await fs.readFile(path.join(root,'fixtures/01-c.u01'))});await expect(page.locator('#error')).toBeVisible();await expect(page.locator('#download-zip')).toBeDisabled();await demo();});
 await check('Native record and command expansion budgets fail closed before insertion',async()=>{const make=(name,size)=>({name,mimeType:'application/octet-stream',buffer:Buffer.alloc(size)});await page.locator('#file-input').setInputFiles(make('too-many-records.u01',256+200001*3));await expect(page.locator('#error pre')).toContainText('RECORD_COUNT');await expect(page.locator('[data-testid="job-card"]')).toHaveCount(3);await expect(page.locator('#download-zip')).toBeDisabled();await demo();await page.locator('#file-input').setInputFiles(Array.from({length:4},(_,i)=>make(`batch-${i}.u01`,256+150000*3)));await expect(page.locator('#error pre')).toContainText('RECORD_COUNT');await expect(page.locator('[data-testid="job-card"]')).toHaveCount(3);await demo();const bytes=Buffer.alloc(256+10003*3);for(let i=0;i<10001;i++)bytes[256+i*3]=0xc9;bytes[256+10001*3]=0xc0;bytes[256+10002*3]=0xf8;await page.locator('#file-input').setInputFiles({name:'command-bomb.u01',mimeType:'application/octet-stream',buffer:bytes});await expect(page.locator('#error pre')).toContainText('NEEDLE_COMMAND_COUNT');await expect(page.locator('#download-zip')).toBeDisabled();await demo();});
 await check('Delayed file read followed by reset stays empty',async()=>{await page.evaluate(()=>{const original=File.prototype.arrayBuffer;window.__originalFileRead=original;File.prototype.arrayBuffer=async function(){await new Promise(r=>setTimeout(r,400));return original.call(this);};});await page.locator('#file-input').setInputFiles(path.join(root,'fixtures/01-c.u01'));await page.locator('#reset-empty').click();await page.waitForTimeout(550);await expect(page.locator('[data-testid="job-card"]')).toHaveCount(0);await expect(page.locator('#download-zip')).toBeDisabled();await page.evaluate(()=>{File.prototype.arrayBuffer=window.__originalFileRead;delete window.__originalFileRead;});});
 await check('Delayed demo followed by reset does not overwrite newer state',async()=>{await page.route('**/fixtures/demo.json',async route=>{await new Promise(r=>setTimeout(r,400));await route.continue();});await page.locator('#load-demo').click();await page.locator('#reset-empty').click();await page.waitForTimeout(550);await expect(page.locator('[data-testid="job-card"]')).toHaveCount(0);await page.unroute('**/fixtures/demo.json');await demo();});
 await check('Export hashing interrupted by edit discards download',async()=>{await page.evaluate(()=>{const original=crypto.subtle.digest.bind(crypto.subtle);window.__originalDigest=original;crypto.subtle.digest=async(...args)=>{await new Promise(r=>setTimeout(r,150));return original(...args);};});let downloaded=false;const onDownload=()=>{downloaded=true;};page.on('download',onDownload);await page.locator('#download-zip').click();await page.locator('#needle-thread-0').fill('X');await page.waitForTimeout(1200);expect(downloaded).toBe(false);await expect(page.locator('#download-zip')).toBeDisabled();page.off('download',onDownload);await page.evaluate(()=>{crypto.subtle.digest=window.__originalDigest;delete window.__originalDigest;});await demo();});
 await check('Hostile thread identity remains inert text',async()=>{const hostile='<img src=x onerror=alert(1)>';await page.locator('#map-0-1').fill(hostile);await page.locator('#optimize').click();await expect(page.locator('#download-zip')).toBeEnabled();await expect(page.locator('img')).toHaveCount(0);expect(await page.locator('#results').textContent()).toContain(hostile);await demo();});
 await check('Mobile Japanese and English fit viewport',async()=>{await page.setViewportSize({width:390,height:844});await page.locator('[data-lang="ja"]').click();await ready();await noOverflow();await page.screenshot({path:path.join(out,'mobile-ja.png'),fullPage:true});await page.locator('[data-lang="en"]').click();await noOverflow();await page.screenshot({path:path.join(out,'mobile-en.png'),fullPage:true});});
 await check('Skip link and controls remain keyboard accessible',async()=>{await page.goto(base);await ready();await page.keyboard.press('Tab');await expect(page.locator('.skip-link')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('#workspace')).toBeFocused();await page.locator('#load-demo').focus();await page.keyboard.press('Enter');await ready();});
 expect(pageErrors).toEqual([]);expect(externalRequests).toEqual([]);
 await fs.writeFile(path.join(out,'browser-results.json'),JSON.stringify({passed:true,browser:await browser.version(),chromiumSandbox:true,baseURL:base,checks,pageErrors,externalRequests,download:'downloaded.zip',print:'loading-checklist.pdf',note:'Actual browser download consumed separately with pinned pystitch and raw byte oracle.'},null,2)+'\n');
}catch(error){await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});await fs.writeFile(path.join(out,'browser-results.json'),JSON.stringify({passed:false,checks,pageErrors,error:error.stack},null,2)+'\n');throw error;}finally{await browser.close();}
